spring:
  data:
    mongodb:
      database: pingpong
      uri: mongodb://192.168.15.101:27017
  application:
    name: ping
server:
  port: 10011
ping:
  work-dir: ${user.home}/pingpong
  cron: "* * * * * ?"
